import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "./components/navbar/navbar";
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })
const pjs = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Onlinekan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pjs.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
